---
# tasks file for nginx

- name: ensure nginx is not installed
  apt:
    name: nginx
    state: absent

- name: ensure nginx is at the latest version
  apt:
    name: nginx
    state: latest

- name: start nginx
  service:
    name: nginx
    state: started
