---

# host for configuring ubuntu server for rails and elixir
- hosts: servers
  remote_user: root
  vars_files:
    - variables.yml
  roles:
    - prerequisites
    - add_user_deploy
    - nodejs
    - yarn
    - elixir
    - ruby
    - bundler

# host for deploying application from local machine
- hosts: my_system
  remote_user: "{{ USER }}"
  vars_files:
    - variables.yml
  tasks:
    - name: run capistrano
      shell: bash -lc "bundle exec cap production deploy"
      args:
        chdir: "{{ APP_DIR }}"

# host for configuring ubuntu server for nginx and logrotate
- hosts: servers
  remote_user: root
  vars_files:
    - variables.yml
  roles:
    - logrotate
    - nginx
