index_servers:
  hosts:
    index_1:
        ansible_connection: ssh
        ansible_host: 18.219.166.183
        ansible_port: 22
        ansible_user: root

deploy_servers:
  hosts:
     ubun:
        ansible_connection: ssh
        ansible_host: "localhost"
        ansible_port: 52022
        ansible_user: 'root'

      # aws:
      #   ansible_connection: ssh
      #   ansible_host: 18.219.166.183
      #   ansible_port: 22
      #   ansible_user: root
