all:
  hosts:
     ubun:
        ansible_connection: ssh
        ansible_host: "localhost"
        ansible_port: 52022
        ansible_user: 'root'

     my_system:
        ansible_connection: ssh
        ansible_host: "localhost"
        ansible_port: 22
        ansible_user: 'Arnab'
