---

- hosts: deploy_servers
  name: Installing nginx and create systemd scripts
  remote_user: root
  become: yes
  vars_files:
    - variables.yml
  roles:
    # - nginx
    # - puma_service_systemd
    - delayed_job_service_systemd
