---

- name: install latest version of logrotate
  apt:
    update_cache: yes
    name: logrotate
    state: latest

- name: setup logrotate configuration in /etc/logrotate.d/
  copy:
    dest: /etc/logrotate.d/{{ item.app_name }}
    owner: root
    group: root
    mode: '0644'
    content: |
      /var/deploy/{{ item.username }}/{{ item.app_name }}/current/log/*.log {
        su {{ item.username }} {{ item.username }}
        daily
        missingok
        rotate 15
        compress
        delaycompress
        notifempty
        copytruncate }
  with_items:
    - "{{ users }}"

- name: Set up cron for daily logrotation of apps
  cron:
    name:  daily log rotation of {{ item.app_name }}
    minute: "0"
    hour: "0"
    user: "{{ item.username }}"
    job: /usr/sbin/logrotate -f /etc/logrotate.d/{{ item.app_name }} > /dev/null
  with_items:
    - "{{ users }}"
