---

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) ALL"
    validate: "visudo -cf %s"

- name: Add sudoer users to wheel group
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
  with_items:
    - "{{ users }}"

- name: Set up authorized keys for users
  authorized_key:
    user: "{{ item.username }}"
    state: present
    manage_dir: yes
    key: "{{ lookup('file', '/home/{{ MY_SYSTEM_ACCOUNT }}/.ssh/id_rsa.pub') }}"
  with_items:
    - "{{ users }}"
