---

- name: create directories using usernames and app_names
  file:
    path: "/var/deploy/{{ item.username }}/{{ item.app_name }}"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0777
    recurse: yes
  with_items:
    - "{{ users }}"

- name: set folder owners
  file:
    path: "/var/deploy/{{ item.username }}"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0777
    recurse: yes
  with_items:
    - "{{ users }}"
