---

- name: create directories using usernames and app_names
  file:
    path: "/var/www/{{ item.username }}/{{ item.app_name }}"
    state: directory
  with_items:
    - "{{ users }}"

- name: set folder owners and modes
  file:
    path: "/var/www/{{ item.username }}"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0777
    recurse: yes
  with_items:
    - "{{ users }}"
