---

- name: create systemd scripts for puma servers
  template:
    src: templates/puma_systemd.tpe
    dest: "/etc/systemd/system/{{ item.app_name }}_puma.service"
    mode: 0777
  with_items:
    - "{{ users }}"

- name: enable puma services( start on boot)
  systemd:
    name: "{{ item.app_name }}_puma.service"
    enabled: yes
    masked: no
  with_items:
    - "{{ users }}"
