---


- name: copy database.yml file
  copy:
    src: "{{ item.app_path_local }}/config/database.yml"
    dest: /var/www/{{ item.username }}/{{ item.app_name }}/shared/config/
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0644
  with_items:
    - "{{ users }}"

# - name: copy credentials.yml.enc files
#   copy:
#     src: "{{ item.app_path_local }}/config/credentials.yml.enc"
#     dest: /var/www/{{ item.username }}/{{ item.app_name }}/shared/config/
#     owner: "{{ item.username }}"
#     group: "{{ item.username }}"
#     mode: 0644
#   with_items:
#     - "{{ users }}"

# - name: copy master.key files
#   copy:
#     src: "{{ item.app_path_local }}/config/master.key"
#     dest: /var/www/{{ item.username }}/{{ item.app_name }}/shared/config/
#     owner: "{{ item.username }}"
#     group: "{{ item.username }}"
#     mode: 0644
#   with_items:
#     - "{{ users }}"

- name: copy secrets.yml file
  copy:
    src: "{{ item.app_path_local }}/config/secrets.yml"
    dest: /var/www/{{ item.username }}/{{ item.app_name }}/shared/config/
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0644
  with_items:
    - "{{ users }}"
