---

- name: install java
  apt:
    name: default-jdk
    state: latest

- name: get apt repo key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: install apt repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elastic-7.x.list
    update_cache: yes

- name: install elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: reload systemd config
  systemd:
    daemon_reload: yes

- name: enable service elasticsearch( start on boot)
  systemd:
    name: elasticsearch
    enabled: yes
    masked: no

- name: ensure elasticsearch is running
  systemd:
    state: started
    name: elasticsearch

# - name: ensure elasticsearch is running
#   service:
#     state: started
#     name: elasticsearch
